version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'Scraper'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'abcd1234'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE_SCHEMA=Scraper
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=abcd1234
      - DATABASE_HOST=db
      - DATABSE_PORT=3306
      - JWT_SECRET=9799b9ad-4791-4114-8365-2f9155c2a23d
      - SECRET=2+y^2**09(+6@9)zo)5pw*2kap!ev=ph@r1x_o!qdmg7lzhh78-s9^3^k5^(b4b%(1ypy-d!3%uifzb^^cw&^e^h621^iyi3z4ek
    expose:
      - 8000
    volumes:
      - media_volume:/app/media

  nginx:
    build: ./ngnix
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - media_volume:/app/media
    depends_on:
      - app

volumes:
  media_volume:
  db_data:
