# Generated by Django 4.1.4 on 2023-01-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_setting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='google_map_link',
            field=models.CharField(default=1, help_text='address (google map link)', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
