# Generated by Django 4.1.4 on 2023-01-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_setting_google_map_link_alter_setting_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='about_us',
        ),
        migrations.AddField(
            model_name='setting',
            name='about_us_1',
            field=models.TextField(default=1, help_text='left side'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='about_us_2',
            field=models.TextField(default=1, help_text='right side'),
            preserve_default=False,
        ),
    ]
