# Generated by Django 4.1.4 on 2022-12-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='name',
            new_name='categorie_name',
        ),
    ]
