# Generated by Django 4.1.4 on 2022-12-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_categorie_categorie_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='parent',
        ),
    ]
