# Generated by Django 4.1.4 on 2022-12-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('on_the_way', 'On the way'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
