# Generated by Django 4.1.4 on 2022-12-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(max_length=1000),
        ),
    ]
