# Generated by Django 4.1.4 on 2022-12-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_description_alter_product_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_link',
            field=models.CharField(max_length=1000),
        ),
    ]
