# Generated by Django 4.1.4 on 2022-12-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['timestamp']},
        ),
    ]
