# Generated by Django 4.1.4 on 2022-12-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['-timestamp']},
        ),
    ]
